#!/bin/bash
gcc $CFILE -o c_is fun
~                                                                                  ~                                                                                  ~      
